sudo: false
language: go
go: go1.5
script:
  - test -z "$(gofmt -s -l -w . | tee /dev/stderr)"
  - go test -v -cover  ./...
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v golang.org/x/tools/cmd/cover
  - go get -t github.com/smartystreets/goconvey
  - go get github.com/jacobsa/oglematchers
