sudo: false

language: go
go:
  - 1.7

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/bradleyfalzon/apicompat/cmd/apicompat

script:
  - go vet -x ./...
  - golint ./...
  - go test -v  ./...
  - go test -covermode=count -coverprofile=profile.cov
  - git branch -av; env
  - git --git-dir /home/travis/gopath/src/github.com/ahmetalpbalkan/go-linq/.git ls-tree master ./
  - test -z "$(apicompat -before master -after HEAD ./... | tee /dev/stderr)"

after_script:
  - goveralls -coverprofile=profile.cov -service=travis-ci
